sudo: required

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake

script:
  - mkdir build
  - cd build/
  - cmake ../
  - make
